# **Error vs Exception 2**

## Exception Handling

JAVA에서 모든 예외가 발생하면 Exception 객체를 생성합니다. 예외를 처리하는 방법에는 크게 2가지가 있습니다. 

1. 직접 try ~ catch 를 이용해서 예외에 대한 최종적인 책임을 지고 처리하는 방식
2. throws Exception을 이용해서 발생한 예외의 책임을 호출하는 쪽이 책임지도록 하는 방식(주로 호출하는 쪽에 예외를 보고할 때 사용합니다.)

다른 메소드의 일부분으로 동작하는 경우엔 던지는 것을 추천

## 예외 잡기(try ~ catch 구문)

로직 중에 예외가 발생할지도 모르는 부분에 try ~ catch구문으로 보험 처리합니다. 

try에는 예외가 발생할 수 있는 로직을 작성하고, catch는 예외 발생시 수행할 로직이 들어갑니다. 

try 중이라도 예외가 발생한 다음의 코드들은 실행되지 않으며 catch 구문으로 넘어갑니다. 

catch 구문은 else if 처럼 여러 개 작성 가능

finally는 예외가 발생하더라도 실행하고 싶은 로직을 작성하며 대표적으로 .close()가 있다.

## 예외 던지기(throws 구문)

예외 처리를 현재 메소드가 직접 처리하지 않고 호출한 곳에다가 예외의 발생 여부를 통보합니다. 호출한 메소드는 이걸 또 던질건지 직접 처리할 건지 정해야한다. 

```java
public class ThrowsEx() {
	public void callA() throws Exception {
		callB();
	}
	
	public void callB() throws Exception {
		callC();
	}
	
	public void callC() throws Exception {
		System.out.println(1 / 0);
	}
	
	public static void main(String[] args) throws Exception {
		ThrowsEx test = new ThrowsEx();
		test.callA();
	}
}
```

```java
// 실행결과
Excecption in thread "main" java.lang.AruthmeticException: / by zero
		at exception.ThrowsEx.call_C(ThrowsEx.java:13)
    at exception.ThrowsEx.call_B(ThrowsEx.java:9)
    at exception.ThrowsEx.call_A(ThrowsEx.java:5)
    at exception.ThrowsEx.main(ThrowsEx.java:18)

```

📚 출처

- [https://gyoogle.dev/blog/computer-language/Java/Error & Exception.html](https://gyoogle.dev/blog/computer-language/Java/Error%20&%20Exception.html)